name: "Laravel Pint Check"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php-code-styling:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Laravel Pint Check
        uses: aglipanci/laravel-pint-action@2.5
        with:
          testMode: true
