name: release-please

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: php
